final LOREM_IPSUM = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consectetur ligula id velit luctus, sit amet maximus velit eleifend. Pellentesque id risus sed libero efficitur consequat. Mauris finibus, dolor ut commodo ultrices, arcu lacus varius justo, ac egestas nunc nisi in nisl. Vivamus sit amet massa nec odio mattis tempor hendrerit non felis. Nullam pharetra dignissim nulla, a molestie nibh laoreet in. Morbi egestas non ante vel cursus. Nunc eu elit quis risus mollis tempus eget vel purus. Sed vehicula hendrerit magna, ut pharetra elit. Quisque semper arcu eu nisi ultricies, ac faucibus nulla suscipit.

Vivamus a massa sapien. Ut mollis, ex sit amet volutpat rutrum, lorem purus vehicula metus, a tristique eros ipsum sit amet nibh. Curabitur sagittis lectus non justo posuere interdum. Vivamus tincidunt id augue ac ullamcorper. Praesent consectetur interdum nisi quis viverra. Phasellus vulputate, lectus in varius faucibus, orci felis malesuada nibh, eget dictum quam neque eu velit. Fusce et tincidunt neque, et molestie lacus. Etiam auctor dui ac nisl finibus maximus. Nullam a elit dictum, imperdiet dolor nec, venenatis dolor. Sed nisl dui, pharetra nec congue eu, posuere ut ex. Aenean pulvinar ex sed nibh consectetur, id molestie turpis ultrices. Vestibulum laoreet ipsum id nibh dapibus mollis. Aenean risus nunc, cursus id turpis non, placerat imperdiet justo.

Mauris venenatis velit risus, cursus aliquet tortor mattis sed. Proin volutpat rhoncus magna, eget tincidunt sem hendrerit a. Donec euismod nulla ligula. Praesent eu lectus leo. Aliquam bibendum massa tellus, in egestas nisi fermentum ultricies. Nam eget metus justo. Nulla sagittis scelerisque fringilla. Phasellus hendrerit massa arcu, nec tempor dolor consectetur non. In dignissim, justo eu convallis scelerisque, orci nunc ullamcorper dui, eget faucibus ipsum nisl non est. Nunc ut sagittis ipsum. Pellentesque tempor aliquam facilisis. Nulla hendrerit placerat mi, ac laoreet velit. Mauris sem eros, hendrerit sit amet suscipit ut, pulvinar ut odio. Suspendisse sagittis enim eu eros volutpat imperdiet.

Maecenas ac consectetur ante. In nec blandit leo, id vestibulum metus. In tincidunt nibh tortor, in cursus lectus porttitor ullamcorper. Vestibulum vel nunc ac purus scelerisque bibendum. Nulla quis lectus augue. Etiam eget nisl nisi. Ut congue massa mattis lectus tincidunt, non tempus nulla elementum. Vestibulum orci arcu, vulputate et massa ut, malesuada placerat tortor. Integer diam nibh, rutrum at ex et, facilisis iaculis lectus. Proin at nulla quis elit maximus ultrices non in magna. Donec posuere nunc at eleifend ornare. Mauris consequat iaculis sem, vitae consectetur est posuere sit amet. Nulla eget augue a ante congue lobortis et nec mauris. Nam eget efficitur enim, eleifend tincidunt enim. Cras nec posuere velit. Praesent at purus nec velit dictum malesuada.

Fusce venenatis sed ante sed fermentum. Vestibulum urna nisl, consequat eu tortor ac, hendrerit hendrerit arcu. Cras aliquam lorem ut semper pulvinar. Aenean tincidunt lacus nec augue tincidunt commodo. Nulla facilisi. Proin ullamcorper metus risus, vel placerat dui iaculis id. Vestibulum tempus diam sem, eu sollicitudin ex mattis eget. Vestibulum sodales tristique scelerisque. Nam nec nulla ut dui vehicula dapibus at eu leo. Nunc fringilla nunc a erat pellentesque mollis. Fusce arcu mauris, posuere elementum eleifend et, tincidunt non lectus. Aliquam erat volutpat.""";
